# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    export PS_VERSION=8.0.23-14
    export PS_REVISION=3558242

    echo ${BUILD_TYPE_MINIMAL}
    PS_MAJOR_VERSION="$(echo ${PS_VERSION}|cut -d'.' -f1,2)"
    MINIMAL=""
    if [ "${BUILD_TYPE_MINIMAL}" = "true" ]; then
      MINIMAL="-minimal"
    fi
    if [ "${PS_MAJOR_VERSION}" = "8.0" ]; then
      export GLIBC_VERSION="2.17"
      if [ -f /etc/redhat-release ] && [ $(grep -c "release 6" /etc/redhat-release) -eq 1 ]; then
        export GLIBC_VERSION="2.12"
      fi
      TARBALL_NAME="Percona-Server-${PS_VERSION}-Linux.x86_64.glibc${GLIBC_VERSION}${MINIMAL}.tar.gz"
      TARBALL_LINK="https://www.percona.com/downloads/TESTING/ps-${PS_VERSION}/"
    elif [ "${PS_MAJOR_VERSION}" = "5.7" ]; then
      TARBALL_NAME="Percona-Server-${PS_VERSION}-Linux.x86_64.glibc2.12${MINIMAL}.tar.gz"
      TARBALL_LINK="https://www.percona.com/downloads/TESTING/ps-${PS_VERSION}/"
    fi
    rm -rf package-testing
    if [ -f /usr/bin/yum ]; then
      sudo yum install -y git wget
    else
      sudo apt install -y git wget lsb-release
    fi
    git clone https://github.com/Percona-QA/package-testing.git --branch ps-tarball-test-linked-libraries --depth 1
    cd package-testing/binary-tarball-tests/ps
    wget -q ${TARBALL_LINK}${TARBALL_NAME}
    ./run.sh || true
  SHELL
end
