---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: oraclelinux10
    image: ${HOME}/qemu-images/oraclelinux-10-amd64.raw
    memory: 2048
    cpus: 2
    disk_size: 32G
    ssh_port: 2271
    ssh_user: cloud-user
    ssh_key: ~/.ssh/id_rsa

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../shared/create.yml
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/converge.yml

verifier:
  name: ansible
