DEB12_EXTENSIONS = ["pageinspect",
                    "plpython3u",
                    "pg_visibility",
                    "pg_buffercache",
                    "pgstattuple",
                    "cube",
                    "pgrowlocks",
                    "unaccent",
                    "tsm_system_rows",
                    "intarray",
                    "seg",
                    "xml2",
                    "intagg",
                    "pltcl",
                    "btree_gist",
                    "refint",
                    "tablefunc",
                    "dict_int",
                    "pg_prewarm",
                    "pg_freespacemap",
                    "pg_trgm",
                    "earthdistance",
                    "pltclu",
                    "bloom",
                    "hstore",
                    "pg_stat_statements",
                    "ltree",
                    "lo",
                    "dblink",
                    "dict_xsyn",
                    "isn",
                    "plperlu",
                    "tcn",
                    "sslinfo",
                    "jsonb_plpython3u",
                    "amcheck",
                    "pgcrypto",
                    "fuzzystrmatch",
                    "tsm_system_time",
                    "uuid-ossp",
                    "postgres_fdw",
                    "citext",
                    "moddatetime",
                    "insert_username",
                    "btree_gin",
                    "hstore_plpython3u",
                    "adminpack",
                    "autoinc",
                    "plperl",
                    "pg_stat_monitor"]

RPM12_EXTENSIONS = ['hstore',
                    'adminpack',
                    'amcheck',
                    'cube',
                    'insert_username',
                    'autoinc',
                    'bloom',
                    'earthdistance',
                    'intagg',
                    'btree_gin',
                    'file_fdw',
                    'fuzzystrmatch',
                    'btree_gist',
                    'intarray',
                    'citext',
                    'dblink',
                    'dict_xsyn',
                    'lo',
                    'dict_int',
                    'isn',
                    'ltree',
                    'moddatetime',
                    'pgrowlocks',
                    'pageinspect',
                    'pg_trgm',
                    'tcn',
                    'pgstattuple',
                    'pg_buffercache',
                    'xml2',
                    'postgres_fdw',
                    'pg_freespacemap',
                    'pg_prewarm',
                    'pg_visibility',
                    'refint',
                    'pgcrypto',
                    'pg_stat_statements',
                    'seg',
                    'sslinfo',
                    'tablefunc',
                    'tsm_system_rows',
                    'tsm_system_time',
                    'plperlu',
                    'unaccent',
                    'uuid-ossp',
                    'pltcl',
                    'pltclu',
                    'plpython2u',
                    'plpythonu',
                    'plperl',
                    'pg_stat_monitor'
                    ]

RPM13_EXTENSIONS = ['hstore',
                    'adminpack',
                    'amcheck',
                    'cube',
                    'insert_username',
                    'autoinc',
                    'bloom',
                    'earthdistance',
                    'intagg',
                    'btree_gin',
                    'file_fdw',
                    'fuzzystrmatch',
                    'btree_gist',
                    'intarray',
                    'citext',
                    'dblink',
                    'dict_xsyn',
                    'lo',
                    'dict_int',
                    'isn',
                    'ltree',
                    'moddatetime',
                    'pgrowlocks',
                    'pageinspect',
                    'pg_trgm',
                    'tcn',
                    'pgstattuple',
                    'pg_buffercache',
                    'xml2',
                    'postgres_fdw',
                    'pg_freespacemap',
                    'pg_prewarm',
                    'pg_visibility',
                    'refint',
                    'pgcrypto',
                    'pg_stat_statements',
                    'seg',
                    'sslinfo',
                    'tablefunc',
                    'tsm_system_rows',
                    'tsm_system_time',
                    'plperlu',
                    'unaccent',
                    'uuid-ossp',
                    'pltcl',
                    'pltclu',
                    'plperl',
                    'pg_stat_monitor'
                    ]


DEB11_EXTENSIONS = ['pageinspect',
                    'plpython3u',
                    'pg_visibility',
                    'pg_buffercache',
                    'file_fdw',
                    'pgstattuple',
                    'cube',
                    'pgrowlocks',
                    'unaccent',
                    'tsm_system_rows',
                    'intarray',
                    'seg',
                    'xml2',
                    'intagg',
                    'pltcl',
                    'btree_gist',
                    'refint',
                    'tablefunc',
                    'dict_int',
                    'pg_prewarm',
                    'pg_freespacemap',
                    'pg_trgm',
                    'earthdistance',
                    'pltclu',
                    'bloom',
                    'hstore',
                    'pg_stat_statements',
                    'ltree',
                    'lo',
                    'dblink',
                    'dict_xsyn',
                    'isn',
                    'plperlu',
                    'tcn',
                    'sslinfo',
                    'jsonb_plpython3u',
                    'amcheck',
                    'pgcrypto',
                    'fuzzystrmatch',
                    'tsm_system_time',
                    'uuid-ossp',
                    'postgres_fdw',
                    'timetravel',
                    'citext',
                    'moddatetime',
                    'insert_username',
                    'btree_gin',
                    'hstore_plpython3u',
                    'adminpack',
                    'autoinc',
                    'plperl'
                    ]

RPM11_EXTENSIONS = ['fuzzystrmatch',
                    'citext',
                    'pltcl',
                    'pltclu',
                    'plperl',
                    'hstore',
                    'plperlu',
                    'hstore_plperl',
                    'adminpack',
                    'hstore_plperlu',
                    'amcheck',
                    'isn',
                    'insert_username',
                    'autoinc',
                    'bloom',
                    'dblink',
                    'btree_gin',
                    'dict_int',
                    'intagg',
                    'dict_xsyn',
                    'btree_gist',
                    'cube',
                    'file_fdw',
                    'intarray',
                    'jsonb_plperl',
                    'pg_visibility',
                    'jsonb_plperlu',
                    'pgstattuple',
                    'lo',
                    'postgres_fdw',
                    'ltree',
                    'moddatetime',
                    'pgcrypto',
                    'pgrowlocks',
                    'refint',
                    'pageinspect',
                    'pg_stat_statements',
                    'pg_buffercache',
                    'seg',
                    'pg_freespacemap',
                    'pg_prewarm',
                    'pg_trgm',
                    'tcn',
                    'xml2',
                    'sslinfo',
                    'tablefunc',
                    'timetravel',
                    'tsm_system_rows',
                    'tsm_system_time',
                    'unaccent',
                    'uuid-ossp',
                    'plpython2u',
                    'plpythonu'
                    ]


def get_extensions_ppg11(distro_type):
    if ("debian" or "ubuntu" or "ubuntu-bionic" or "ubuntu-focal") in distro_type:
        return DEB11_EXTENSIONS
    return RPM11_EXTENSIONS


def get_extensions_ppg12(distro_type):
    if ("debian" or "ubuntu" or "ubuntu-bionic" or "ubuntu-focal") in distro_type:
        return DEB12_EXTENSIONS
    return RPM12_EXTENSIONS


def get_extensions_ppg13(distro_type):
    if ("debian" or "ubuntu" or "ubuntu-bionic" or "ubuntu-focal") in distro_type:
        return DEB12_EXTENSIONS
    return RPM13_EXTENSIONS
