pgbackrest = {"ppg-11.5": {"version": "2.16",
                           "binary_version": "pgBackRest 2.16"},
              "ppg-11.6": {"version": "2.20",
                           "binary_version": "pgBackRest 2.20"},
              "ppg-11.7": {"version": "2.25",
                           "binary_version": "pgBackRest 2.25"},
              "ppg-11.8": {"version": "2.27",
                           "binary_version": "pgBackRest 2.27"},
              "ppg-11.9": {"version": "2.27",
                           "binary_version": "pgBackRest 2.27"},
              "ppg-12.2": {"version": "2.26",
                           "binary_version": "pgBackRest 2.26"},
              "ppg-12.3": {"version": "2.27",
                           "binary_version": "pgBackRest 2.27"},
              "ppg-12.4": {"version": "2.27",
                           "binary_version": "pgBackRest 2.27"}
              }
