pipeline {
  agent {
  label 'micro-amazon'
  }
  environment {
      PATH = '/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin'
  }
  parameters {
        choice(
            name: 'PLATFORM',
            description: 'For what platform (OS) need to test',
            choices: [
                'centos-7',
                'debian-9',
                'debian-10',
                'ubuntu-18.04',
                'rhel8'
            ]
        )
        choice(
            name: 'install_repo',
            description: 'Repo for testing',
            choices: [
                'testing',
                'experimental',
                'main',
            ]
        )
        choice(
            name: 'psmdb_to_test',
            description: 'PSMDB for testing',
            choices: [
                'psmdb36',
                'psmdb40',
                'psmdb36',
            ]
        )
  }
  stages {
    stage('Set build name'){
      steps {
                script {
                    currentBuild.displayName = "${env.BUILD_NUMBER}-${env.PLATFORM}"
                }
            }
        }
    stage ('Setup Environment Variables') {
      steps {
       script {
       vms = readYaml (file: 'molecule/configuration.yml')
       env.IMAGE = vms."${PLATFORM}".image
       env.USER = vms."${PLATFORM}".user
       env.SUBNET = vms."${PLATFORM}".subnet
       env.AWS_DEFAULT_REGION = vms."${PLATFORM}".aws_default_region
       env.INSTANCE_TYPE = vms."${PLATFORM}".instance_type
        }
       }
      }
    stage ('Prepare') {
      steps {
        checkout scm
        sh '''
            sudo yum install -y gcc python3 python3-pip python3-devel libselinux-python openssl-devel
            sudo mkdir -p /usr/local/lib64/python3.7/site-packages
            sudo rsync -aHv /usr/lib64/python2.7/site-packages/*selinux* /usr/local/lib64/python3.7/site-packages/
            pip3 install --user pytest molecule ansible wheel boto boto3 paramiko selinux 'molecule[ec2]'
        '''
      }
    }
    stage ('Create virtual machines') {
      steps {
       withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: '4462f2e5-f01c-4e3f-9586-2ffcf5bf366a', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
          sh '''
              cd molecule/pbm
              python3 -m molecule create
          '''
      }
     }
    }
    stage ('Run playbook for test') {
      steps {
        sh '''
            cd molecule/pbm
            python3 -m molecule converge
        '''
      }
    }
    stage ('Start testinfra tests') {
      steps {
        sh '''
            cd molecule/pbm
            python3 -m molecule verify
        '''
        junit 'molecule/pbm/molecule/default/*.xml'
      }
    }
    stage ('Start packages deletion') {
      steps {
        sh '''
            cd molecule/pbm
            python3 -m molecule cleanup
        '''
      }
    }
  }
  post {
    always {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: '4462f2e5-f01c-4e3f-9586-2ffcf5bf366a', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
        sh '''
            cd molecule/pbm
            python3 -m molecule destroy
        '''
     }
    }
  }
}