USE world2;
ALTER TABLE City DROP FOREIGN KEY city_ibfk_1;
SET SESSION tokudb_row_format = TOKUDB_LZMA;
ALTER TABLE City Engine=TokuDB;
OPTIMIZE TABLE City;
SHOW CREATE TABLE City;

SET SESSION tokudb_row_format = TOKUDB_ZLIB;
ALTER TABLE City;
OPTIMIZE TABLE City;
SHOW CREATE TABLE City;

SET SESSION tokudb_row_format = TOKUDB_QUICKLZ;
ALTER TABLE City;
OPTIMIZE TABLE City;
SHOW CREATE TABLE City;

SET SESSION tokudb_row_format = TOKUDB_SNAPPY;
ALTER TABLE City;
OPTIMIZE TABLE City;
SHOW CREATE TABLE City;
