---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: ubuntu24
    image: ${HOME}/qemu-images/noble-server-cloudimg-amd64.raw
    memory: 2048
    cpus: 2
    disk_size: 20G
    ssh_port: 2235
    ssh_user: ubuntu
    ssh_key: ~/.ssh/id_rsa

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../shared/create.yml
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/converge.yml

verifier:
  name: ansible
