  - name: "[PXB-COMPRESSION] Install lz4 and zstd (RedHat)"
    yum:
      name: [lz4, zstd]
    when: ansible_os_family == "RedHat"

  - name: "[PXB-COMPRESSION] Install lz4 and zstd (Debian/Ubuntu)"
    apt:
      name: [lz4, zstd]
    when: ansible_os_family == "Debian" and ansible_distribution_release != "bionic"

  - name: "[PXB-COMPRESSION] Install lz4 and zstd (Bionic)"
    apt:
      name: [liblz4-tool, zstd]
    when: ansible_os_family == "Debian" and ansible_distribution_release == "bionic"

  - name: "[PXB-COMPRESSION] Run backup with lz4"
    command: /usr/bin/xtrabackup --backup --user=root --target-dir=/tmp/backup_l/ --compress=lz4 --compress-threads=10

  - name: "[PXB-COMPRESSION] Decompress lz4 backup"
    command: /usr/bin/xtrabackup --decompress --user=root --target-dir=/tmp/backup_l/

  - name: "[PXB-COMPRESSION] Prepare lz4 backup"
    command: /usr/bin/xtrabackup --prepare --user=root --target-dir=/tmp/backup_l/

  - name: "[PXB-COMPRESSION] Run backup with zstd"
    command: /usr/bin/xtrabackup --backup --user=root --target-dir=/tmp/backup_z/ --compress=zstd --compress-threads=10

  - name: "[PXB-COMPRESSION] Decompress zstd backup"
    command: /usr/bin/xtrabackup --decompress --user=root --target-dir=/tmp/backup_z/

  - name: "[PXB-COMPRESSION] Prepare zstd backup"
    command: /usr/bin/xtrabackup --prepare --user=root --target-dir=/tmp/backup_z/
