pipeline {
  agent {
  label 'micro-amazon'
  }
  environment {
      PATH = '/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin'
  }
  parameters {
        choice(
            name: 'PLATFORM',
            description: 'For what platform (OS) need to test',
            choices: [
                'centos-7',
                'debian-9',
                'debian-10',
                'ubuntu-bionic',
                'rhel8'
            ]
        )
        choice(
            name: 'REPO',
            description: 'Repo for testing',
            choices: [
                'testing',
                'experimental',
                'release'
            ]
        )

  }
  stages {
    stage('Set build name'){
      steps {
                script {
                    currentBuild.displayName = "${env.BUILD_NUMBER}-${env.PLATFORM}"
                }
            }
        }
    stage ('Setup Environment Variables') {
      steps {
       script {
       vms = readYaml (file: 'molecule/configuration.yml')
       env.IMAGE = vms."${PLATFORM}".image
       env.USER = vms."${PLATFORM}".user
       env.SUBNET = vms."${PLATFORM}".subnet
       env.AWS_DEFAULT_REGION = vms."${PLATFORM}".aws_default_region
       env.INSTANCE_TYPE = vms."${PLATFORM}".instance_type
       env.ROOT_DEVICE_NAME = vms."${PLATFORM}".root_device_name
        }
       }
      }
    stage ('Prepare') {
      steps {
        checkout scm
        sh '''
            sudo yum install -y gcc python3-pip python3-devel libselinux-python openssl-devel
            sudo mkdir -p /usr/local/lib64/python3.7/site-packages
            sudo rsync -aHv /usr/lib64/python2.7/site-packages/*selinux* /usr/local/lib64/python3.7/site-packages/
            pip3 install --user pytest molecule ansible wheel boto boto3 paramiko selinux 'molecule[ec2]'
        '''
      }
    }
    stage ('Create virtual machines') {
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'MOLECULE_AWS_PRIVATE_KEY', keyFileVariable: 'MOLECULE_AWS_PRIVATE_KEY', passphraseVariable: '', usernameVariable: ''),
        [$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: '4462f2e5-f01c-4e3f-9586-2ffcf5bf366a', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
          sh '''
              cd molecule/pg-11-with-vanila-components
              molecule create -s pg-11-with-vanila-components
          '''
        }
      }
    }
    stage ('Run playbook for test') {
      steps {
        sh '''
            cd molecule/pg-11-with-vanila-components
            molecule converge -s pg-11-with-vanila-components
        '''
      }
    }
    stage ('Start testinfra tests') {
      steps {
        sh '''
            cd molecule/pg-11-with-vanila-components
            molecule verify -s pg-11-with-vanila-components
        '''
        junit 'molecule/pg-11-with-vanila-components/molecule/pg-11-with-vanila-components/report.xml'
      }
    }
    stage ('Start packages deletion') {
      steps {
        sh '''
            cd molecule/pg-11-with-vanila-components
            molecule cleanup -s pg-11-with-vanila-components
        '''
      }
    }
  }
  post {
    always {
      withCredentials([sshUserPrivateKey(credentialsId: 'MOLECULE_AWS_PRIVATE_KEY', keyFileVariable: 'MOLECULE_AWS_PRIVATE_KEY', passphraseVariable: '', usernameVariable: ''),
      [$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: '4462f2e5-f01c-4e3f-9586-2ffcf5bf366a', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
        sh '''
            cd molecule/pg-11-with-vanila-components
            molecule destroy -s pg-11-with-vanila-components
        '''
      }
    }
  }
}
