pipeline {
  agent { label 'qaserver-03' }
  parameters {
        choice(name: 'ROLE', choices: ['pg-11', 'pbm', 'pbm-upgrade'], description: 'Role for testing.')
    }
  stages {
    stage ('Get latest code') {
      steps {
        checkout scm
      }
    }

    stage ('Setup Python virtual environment') {
      steps {
        sh '''
        python3 -m venv virtenv
        source virtenv/bin/activate
        pip install pytest molecule ansible wheel  python-vagrant paramiko
        '''
      }
    }

    stage ('Display versions') {
      steps {
        sh '''
          source virtenv/bin/activate
          docker -v
          python -V
          ansible --version
          molecule --version
        '''
      }
    }

    stage ('Molecule test') {
      steps {
        script {
            if  (params.ROLE == 'pg-11') {
                 sh '''
                      source virtenv/bin/activate
                      cd molecule/pg-11
                      molecule test
                 '''
             }
             else if (params.role == 'pbm') {
                   sh '''
                      source virtenv/bin/activate
                      cd molecule/pbm
                      molecule test
                 '''
                 }
            }
        }
    }
  }
}