pipeline {
  agent { label 'qaserver-03' }
  properties([
     parameters([
        choice(
        choices: ['pg-11', 'pbm'],
         description: 'Role for testing',
         name: 'role')
     ])
   ])
  stages {
    stage ('Get latest code') {
      steps {
        checkout scm
      }
    }

    stage ('Setup Python virtual environment') {
      steps {
        sh '''
        python3 -m venv virtenv
        source virtenv/bin/activate
        pip install pytest molecule ansible wheel  python-vagrant paramiko
        '''
      }
    }

    stage ('Display versions') {
      steps {
        sh '''
          source virtenv/bin/activate
          docker -v
          python -V
          ansible --version
          molecule --version
        '''
      }
    }

    stage ('Molecule test') {
      steps {
        sh '''
            source virtenv/bin/activate
        '''
        script {
            if  (params.role == 'pg-11') {
                 sh '''
                      cd molecule/pg-11
                      molecule test
                 '''
             }
             elif (params.role == 'pbm)' {
                   sh '''
                      cd molecule/pbm
                      molecule test
                 '''
                 }
            }
        }
    }
  }
}