import os

from molecule.ppg.tests.versions.patroni import patroni
from molecule.ppg.tests.versions.pgbackrest import pgbackrest
from molecule.ppg.tests.versions.pgaudit import pgaudit
from molecule.ppg.tests.versions.pg_repack import pgrepack
from molecule.ppg.tests.versions.ppg import get_ppg_versions

MAJOR_VER = "12"
if "11" in os.getenv("VERSION"):
    MAJOR_VER = "11"


def get_settings(distro_type):
    ppg_versions = get_ppg_versions(distro_type)

    return {"ppg-11.9": {"version": "11.9",
                         "deb_pkg_ver": ppg_versions["ppg-11.9"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-11.9"]['deb_packages'],
                         "percona-postgresql-common": '216',
                         "percona-postgresql-client-common": "216",
                         "libpq_version": "110009",
                         "pgaudit": pgaudit['ppg-11.9'],
                         "pgbackrest": pgbackrest['ppg-11.9'],
                         "patroni": patroni['ppg-11.9'],
                         "pgrepack": pgrepack['ppg-11.9'],
                         "pgrepack_package_rpm": 'percona-pg_repack11',
                         "pgrepack_package_deb": "percona-postgresql-11-repack",
                         "libpq": "Version of libpq: 110009",
                         "deb_provides": ppg_versions["ppg-11.9"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-11.9"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-11.9"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-11.9"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-11.9"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-11.9"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-11.9"]['deb_files'],
                         "extensions": ppg_versions["ppg-11.9"]['extensions'],
                         "languages": ppg_versions["ppg-11.9"]['languages']
                         },
            "ppg-11.8": {"version": "11.8",
                         "deb_pkg_ver": ppg_versions["ppg-11.8"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-11.8"]['deb_packages'],
                         "percona-postgresql-common": '215',
                         "percona-postgresql-client-common": "215",
                         "libpq_version": "110008",
                         "pgaudit": pgaudit['ppg-11.8'],
                         "pgbackrest": pgbackrest['ppg-11.8'],
                         "patroni": patroni['ppg-11.8'],
                         "pgrepack": pgrepack['ppg-11.8'],
                         "pgrepack_package_rpm": 'percona-pg_repack11',
                         "pgrepack_package_deb": "percona-postgresql-11-repack",
                         "libpq": "Version of libpq: 110008",
                         "deb_provides": ppg_versions["ppg-11.8"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-11.8"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-11.8"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-11.8"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-11.8"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-11.8"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-11.8"]['deb_files'],
                         "extensions": ppg_versions["ppg-11.8"]['extensions'],
                         "languages": ppg_versions["ppg-11.8"]['languages']
                         },
            "ppg-11.7": {"version": "11.7",
                         "deb_pkg_ver": ppg_versions["ppg-11.7"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-11.7"]['deb_packages'],
                         "percona-postgresql-common": '214',
                         "percona-postgresql-client-common": "214",
                         "libpq_version": "110007",
                         "pgaudit": pgaudit['ppg-11.7'],
                         "pgbackrest": pgbackrest['ppg-11.7'],
                         "patroni": patroni['ppg-11.7'],
                         "pgrepack": pgrepack['ppg-11.7'],
                         "libpq": "Version of libpq: 110007",
                         "deb_provides": ppg_versions["ppg-11.7"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-11.7"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-11.7"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-11.7"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-11.7"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-11.7"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-11.7"]['deb_files'],
                         "extensions": ppg_versions["ppg-11.7"]['extensions'],
                         "languages": ppg_versions["ppg-11.7"]['languages']
                         },
            "ppg-11.6": {"version": "11.6",
                         "deb_pkg_ver": ppg_versions["ppg-11.6"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-11.6"]['deb_packages'],
                         "percona-postgresql-common": '210',
                         "percona-postgresql-client-common": "210",
                         "libpq_version": "110006",
                         "pgaudit": pgaudit['ppg-11.6'],
                         "pgbackrest": pgbackrest['ppg-11.6'],
                         "patroni": patroni['ppg-11.6'],
                         "pgrepack": pgrepack['ppg-11.6'],
                         "libpq": "Version of libpq: 110006",
                         "deb_provides": ppg_versions["ppg-11.6"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-11.6"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-11.6"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-11.6"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-11.6"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-11.6"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-11.6"]['deb_files'],
                         "extensions": ppg_versions["ppg-11.6"]['extensions'],
                         "languages": ppg_versions["ppg-11.6"]['languages']
                         },
            "ppg-11.5": {"version": "11.5",
                         "deb_pkg_ver": ppg_versions["ppg-11.5"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-11.5"]['deb_packages'],
                         "percona-postgresql-common": '204',
                         "percona-postgresql-client-common": "204",
                         "libpq_version": "110005",
                         "deb_provides": ppg_versions["ppg-11.5"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-11.5"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-11.5"]['rpm_provides'],
                         "pgaudit": pgaudit['ppg-11.5'],
                         "pgbackrest": pgbackrest['ppg-11.5'],
                         "patroni": patroni['ppg-11.5'],
                         "pgrepack": pgrepack['ppg-11.5'],
                         "libpq": "Version of libpq: 110005"
                         },
            "ppg-12.2": {"version": "12.2",
                         "deb_pkg_ver": ppg_versions["ppg-12.2"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-12.2"]['deb_packages'],
                         "percona-postgresql-common": '214',
                         "percona-postgresql-client-common": "214",
                         "libpq_version": "120002",
                         "pgaudit": pgaudit['ppg-12.2'],
                         "pgbackrest": pgbackrest['ppg-12.2'],
                         "patroni": patroni['ppg-12.2'],
                         "pgrepack": pgrepack['ppg-12.2'],
                         "libpq": "Version of libpq: 120002",
                         "deb_provides":  ppg_versions["ppg-12.2"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-12.2"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-12.2"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-12.2"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-12.2"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-12.2"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-12.2"]['deb_files'],
                         "extensions": ppg_versions["ppg-12.2"]['extensions'],
                         "languages": ppg_versions["ppg-12.2"]['languages']
                         },
            "ppg-12.3": {"version": "12.3",
                         "deb_pkg_ver": ppg_versions["ppg-12.3"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-12.3"]['deb_packages'],
                         "percona-postgresql-common": '215',
                         "percona-postgresql-client-common": "215",
                         "libpq_version": "120003",
                         "pgaudit": pgaudit['ppg-12.3'],
                         "pgbackrest": pgbackrest['ppg-12.3'],
                         "patroni": patroni['ppg-12.3'],
                         "pgrepack": pgrepack['ppg-12.3'],
                         "pgrepack_package_rpm": 'percona-pg_repack12',
                         "pgrepack_package_deb": "percona-postgresql-12-repack",
                         "libpq": "Version of libpq: 120003",
                         "deb_provides":  ppg_versions["ppg-12.3"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-12.3"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-12.3"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-12.3"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-12.3"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-12.3"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-12.3"]['deb_files'],
                         "extensions": ppg_versions["ppg-12.3"]['extensions'],
                         "languages": ppg_versions["ppg-12.3"]['languages']
                         },
            "ppg-12.4": {"version": "12.4",
                         "deb_pkg_ver": ppg_versions["ppg-12.4"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-12.4"]['deb_packages'],
                         "percona-postgresql-common": '216',
                         "percona-postgresql-client-common": "216",
                         "libpq_version": "120004",
                         "pgaudit": pgaudit['ppg-12.4'],
                         "pgbackrest": pgbackrest['ppg-12.4'],
                         "patroni": patroni['ppg-12.4'],
                         "pgrepack": pgrepack['ppg-12.4'],
                         "pgrepack_package_rpm": 'percona-pg_repack12',
                         "pgrepack_package_deb": "percona-postgresql-12-repack",
                         "libpq": "Version of libpq: 120004",
                         "deb_provides": ppg_versions["ppg-12.4"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-12.4"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-12.4"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-12.4"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-12.4"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-12.4"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-12.4"]['deb_files'],
                         "extensions": ppg_versions["ppg-12.4"]['extensions'],
                         "languages": ppg_versions["ppg-12.4"]['languages']
                         },
            "ppg-13.0": {"version": "13.0",
                         "deb_pkg_ver": ppg_versions["ppg-13.0"]['deb_pkg_ver'],
                         "deb_packages": ppg_versions["ppg-13.0"]['deb_packages'],
                         "percona-postgresql-common": '216',
                         "percona-postgresql-client-common": "216",
                         "libpq_version": "130000",
                         "pgaudit": pgaudit['ppg-13.0'],
                         "pgbackrest": pgbackrest['ppg-13.0'],
                         "patroni": patroni['ppg-13.0'],
                         "pgrepack": pgrepack['ppg-13.0'],
                         "pgrepack_package_rpm": 'percona-pg_repack12',
                         "pgrepack_package_deb": "percona-postgresql-12-repack",
                         "libpq": "Version of libpq: 130000",
                         "deb_provides": ppg_versions["ppg-13.0"]['deb_provides'],
                         "rpm7_provides": ppg_versions["ppg-13.0"]['rpm7_provides'],
                         'rpm_provides': ppg_versions["ppg-13.0"]['rpm_provides'],
                         "rpm_packages": ppg_versions["ppg-13.0"]['rpm_packages'],
                         "rpm7_packages": ppg_versions["ppg-13.0"]['rpm7_packages'],
                         "rhel_files": ppg_versions["ppg-13.0"]['rhel_files'],
                         "deb_files": ppg_versions["ppg-13.0"]['deb_files'],
                         "extensions": ppg_versions["ppg-13.0"]['extensions'],
                         "languages": ppg_versions["ppg-13.0"]['languages']
            }
    }
