---
# tasks file for pdps
  - name: include playbook for removing Percona repo
    include_tasks: ../../../tasks/remove_percona_repository.yml

  - name: Install percona release
    include_tasks: ../../tasks/install_percona_release.yml

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int < 8

  - name: clean and update dnf cache
    shell: |
      dnf clean all
      dnf makecache
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int >= 8

  - name: disable the mariadb module on RHEL/CentOS 8+
    command: dnf module disable mariadb -y
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int == 8

  - set_fact:
      major_repo: "{{ lookup('env', 'MAJOR_REPO') }}"

  - name: Setup the PDMYSQL repo pdps-{{ version }}
    command: percona-release setup -y pdps-{{ version }}
    vars:
      version: "{{ lookup('env', 'VERSION').split('-')[0] }}"
    when: not major_repo

  - name: enable the major pdps-{{ version }} {{ repo }}
    command: percona-release enable-only pdps-{{ version }} {{ repo }}
    vars:
      repo: "{{ lookup('env', 'REPO') }}"
      version: >-
        {{
          '97-lts' if '9.7' in lookup('env', 'VERSION')
          else '9x-innovation' if '9.' in lookup('env', 'VERSION')
          else '84-lts' if '8.4' in lookup('env', 'VERSION')
          else '8x-innovation'
        }}
    when: major_repo

#  - name: install Percona Toolkit new deb packages
#    include_tasks: ../../../tasks/install_pt.yml

# revert order once pt issue(DISTMYSQL-400) is resolved for OL8    
  - name: disable the mysql module on RHEL/CentOS 8+
    command: dnf module disable mysql -y
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int == 8

  - name: clean yum
    shell: |
      yum clean all
      yum makecache
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int < 8

  - name: clean dnf
    shell: |
      dnf clean all
      dnf makecache
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int >= 8

  - name: Install Percona Server packages
    include_tasks: >-
      {{
        '../../../../tasks/install_ps97.yml'
        if '9.7' in lookup('env', 'VERSION')
        else '../../../../tasks/install_ps84.yml'
        if '8.4' in lookup('env', 'VERSION')
        else '../../../../tasks/install_ps_innovation.yml'
      }}

  - name: install Percona XtraBackup {{ major_release_version }} packages
    include_tasks: ../../../tasks/install_pxb_innovation.yml
    vars:
      major_release_version: "{{ lookup('env', 'VERSION').split('.')[:2] | join('') }}"

  - name: Set ProxySQL package name
    set_fact:
      proxysql_package: >-
        {{
          'proxysql3'
          if lookup('env', 'PROXYSQL_VERSION').startswith('3.')
          else 'proxysql2'
        }}

  - name: Install ProxySQL deb package
    apt:
      name: "{{ proxysql_package }}"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Install ProxySQL rpm package with dnf
    dnf:
      name: "{{ proxysql_package }}"
      state: latest
      update_cache: yes
    when:
      - ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon']
      - ansible_facts['distribution_major_version'] | int > 8


  #install initscripts-service manually on OL9 till DISTMYSQL-300 is fixed
  - name: install init scripts for OL9
    dnf:
      name: "{{ packages }}"
    vars:
      packages:
      - initscripts-service
    when: ansible_facts['distribution'] in ['OracleLinux'] and ansible_facts['distribution_major_version'] | int == 9

  - name: start proxysql service
    command: service proxysql start
    when:
      - ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon']
      - ansible_facts['distribution_major_version'] | int > 8

  - name: stop proxysql service
    command: service proxysql stop
    when:
      - ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon']
      - ansible_facts['distribution_major_version'] | int > 8

  - name: start proxysql service
    command: service proxysql start
    when:
      - ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon']
      - ansible_facts['distribution_major_version'] | int > 8

  - name: install orchestrator new deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
        - percona-orchestrator-cli
        - percona-orchestrator-client
        - percona-orchestrator
    when: ansible_os_family == "Debian"

  - name: install orchestrator rpm packages with yum
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - percona-orchestrator-cli
        - percona-orchestrator-client
        - percona-orchestrator
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int < 8

  - name: install orchestrator rpm packages with dnf
    dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - percona-orchestrator-cli
        - percona-orchestrator-client
        - percona-orchestrator
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int >= 8

  - name: start mysql service
    service: name=mysql state=started

  - name: download package-testing repo with wget
    command: "{{ item }}"
    with_items:
    - rm -rf /package-testing
    - rm -f master.zip
    - wget --no-check-certificate -O master.zip "https://github.com/{{ git_account }}/package-testing/archive/{{ branch }}.zip"
    - unzip master.zip
    - rm -f master.zip
    - mv "package-testing-{{ branch }}" /package-testing
    vars:
      branch: "{{ lookup('env', 'TESTING_BRANCH') }}"
      git_account: "{{ lookup('env', 'TESTING_GIT_ACCOUNT') | default('Percona-QA', true) }}"

  - name: set root password on centos
    command: /package-testing/setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: restart mysql service
    service: name=mysql state=restarted

#  - name: Verify telemetry version and package installation
#    command: /package-testing/check_tel_ver_pack.sh

  - name: install percona-mysql-shell package for RHEL/CentOS with yum
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-shell
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int < 8

  - name: install percona-mysql-shell package for RHEL/CentOS with dnf
    dnf:
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-shell
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int >= 8

  - name: install percona-mysql-shell package for Debian/Ubuntu
    apt:
      update_cache: yes
      state: present
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-shell
    when: ansible_os_family == "Debian"

  - name: install percona-mysql-router package for RHEL/CentOS with yum
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-router
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int < 8

  - name: install percona-mysql-router package for RHEL/CentOS with dnf
    dnf:
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-router
    when: ansible_facts['distribution'] in ['RedHat','CentOS','OracleLinux','Amazon'] and ansible_facts['distribution_major_version'] | int >= 8

  - name: install percona-mysql-router package for Debian/Ubuntu
    apt:
      update_cache: yes
      state: present
      name: "{{ packages }}"
    vars:
      packages:
      - percona-mysql-router
    when: ansible_os_family == "Debian"

  - name: start mysql service
    service: name=mysql state=started enabled=yes
