pipeline {
  agent { label 'docker' }
  parameters {
    choice(name: 'DOCKER_ACC', choices: ['percona','perconalab'], description: 'Docker repo to use: percona or perconalab')
    choice(
            choices: ['proxysql2', 'proxysql3'],
            description: 'Choose the product version to test',
            name: 'DOCKER_PRODUCT'
        )
    string(name: 'PROXYSQL_VERSION', defaultValue: '2.7.3-1.1', description: 'Full proxysql version')
  }
  stages {
    stage('Prepare') {
      steps {
          script {
            currentBuild.displayName = "#${BUILD_NUMBER}-${PROXYSQL_VERSION}"
            currentBuild.description = "${DOCKER_ACC}"
          }
         }
        }
    stage("Run parallel") {
        parallel {
      stage ('Run trivy analyzer') {
        steps {
            sh """
                sudo yum install -y wget git
                TRIVY_VERSION="0.69.3"
                ARCH=\$(uname -m)
                if [[ "\$ARCH" == "aarch64" ]]; then
                    ARCH_NAME="ARM64"
                    TRIVY_CHECKSUM="7e3924a974e912e57b4a99f65ece7931f8079584dae12eb7845024f97087bdfd"
                elif [[ "\$ARCH" == "x86_64" ]]; then
                    ARCH_NAME="64bit"
                    TRIVY_CHECKSUM="1816b632dfe529869c740c0913e36bd1629cb7688bd5634f4a858c1d57c88b75"
                else
                    echo "Unsupported architecture: \$ARCH"
                    exit 1
                fi
                echo "Detected architecture: \$ARCH, using Trivy for Linux-\$ARCH_NAME"
                wget https://github.com/aquasecurity/trivy/releases/download/v\${TRIVY_VERSION}/trivy_\${TRIVY_VERSION}_Linux-\${ARCH_NAME}.tar.gz
                echo "\${TRIVY_CHECKSUM}  trivy_\${TRIVY_VERSION}_Linux-\${ARCH_NAME}.tar.gz" | sha256sum -c -
                sudo tar zxvf trivy_\${TRIVY_VERSION}_Linux-\${ARCH_NAME}.tar.gz -C /usr/local/bin/
                wget https://raw.githubusercontent.com/aquasecurity/trivy/v\${TRIVY_VERSION}/contrib/junit.tpl
                /usr/local/bin/trivy -q image --format template --template @junit.tpl  -o trivy-hight-junit.xml \
                --timeout 10m0s --ignore-unfixed --exit-code 1 --severity HIGH,CRITICAL ${DOCKER_ACC}/${DOCKER_PRODUCT}:${PROXYSQL_VERSION}
            """            
         } //end steps
         post {
           always {
                    junit testResults: "*-junit.xml", keepLongStdio: true, allowEmptyResults: true, skipPublishingChecks: true
                }
        }
      } //end Run trivy analyzer
     
      stage('Run tests') {
        steps {
            sh '''
              export PATH=${PATH}:~/.local/bin
              sudo yum install -y python3 python3-pip
              rm -rf package-testing
              git clone -b master https://github.com/Percona-QA/package-testing.git --depth 1
              cd package-testing/docker-image-tests/proxysql
              pip3 install --user -r requirements.txt
              ./run.sh
            '''
        } //end steps
        post {
          always {
          junit 'package-testing/docker-image-tests/proxysql/report.xml'
        }
       }
     } 
    } 
   } 
  }
}
