pipeline {
  agent { label 'docker' }
  parameters {
    choice(name: 'DOCKER_ACC', choices: ['percona','perconalab'], description: 'Docker repo to use: percona or perconalab')
    choice(
            choices: ['proxysql2', 'proxysql3'],
            description: 'Choose the product version to test',
            name: 'DOCKER_PRODUCT'
        )
  }
  stages {
    stage('SET PROXYSQL_VERSION') {
        steps {
          script {
            sh '''
              rm -rf /package-testing
              rm -f master.zip
              wget https://github.com/kaushikpuneet07/package-testing/archive/fix-docker.zip
              unzip fix-docker.zip
              rm -f fix-docker.zip
              mv "package-testing-fix-docker" package-testing
            '''
                    
            def VERSION = sh(
                script: '''grep ${DOCKER_PRODUCT}_VERSION VERSIONS | awk -F= '{print \$2}' | sed 's/"//g' ''',
                returnStdout: true
                ).trim()

             env.PROXYSQL_VERSION = "${VERSION}"

             echo "PROXYSQL_VERSION fetched: ${env.PROXYSQL_VERSION}"

          }
       }
     }
    stage('Set environmental variable'){
      steps{
        script {
                    // Now, you can access these global environment variables
          echo "Using PROXYSQL_VERSION: ${env.PROXYSQL_VERSION}"
                }
            }
        }
    stage('Prepare') {
      steps {
          script {
            currentBuild.displayName = "#${BUILD_NUMBER}-${PROXYSQL_VERSION}"
            currentBuild.description = "${DOCKER_ACC}"
          }
         }
        }
    stage("Run parallel") {
        parallel {
      stage ('Run trivy analyzer') {
        steps {
            sh """
              sudo yum install -y curl wget git
              TRIVY_VERSION=\$(curl --silent 'https://api.github.com/repos/aquasecurity/trivy/releases/latest' | grep '"tag_name":' | tr -d '"' | sed -E 's/.*v(.+),.*/\\1/')
              wget https://github.com/aquasecurity/trivy/releases/download/v\${TRIVY_VERSION}/trivy_\${TRIVY_VERSION}_Linux-64bit.tar.gz
              sudo tar zxvf trivy_\${TRIVY_VERSION}_Linux-64bit.tar.gz -C /usr/local/bin/
              wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl
              /usr/local/bin/trivy -q image --format template --template @junit.tpl  -o trivy-hight-junit.xml \
              --timeout 10m0s --ignore-unfixed --exit-code 1 --severity HIGH,CRITICAL ${DOCKER_ACC}/${DOCKER_PRODUCT}:${PROXYSQL_VERSION}
            """
         } //end steps
         post {
           always {
                    junit testResults: "*-junit.xml", keepLongStdio: true, allowEmptyResults: true, skipPublishingChecks: true
                }
        }
      } //end Run trivy analyzer
     
      stage('Run tests') {
        steps {
            sh '''
              export PATH=${PATH}:~/.local/bin
              sudo yum install -y python3 python3-pip
              rm -rf package-testing
              git clone -b proxy-docker https://github.com/kaushikpuneet07/package-testing.git --depth 1
              cd package-testing/docker-image-tests/proxysql
              pip3 install --user -r requirements.txt
              ./run.sh
            '''
        } //end steps
        post {
          always {
          junit 'package-testing/docker-image-tests/proxysql/report.xml'
        }
       }
     } 
    } 
   } 
  }
}
