pipeline {
  agent {
  label 'micro-amazon'
  }
  environment {
      PATH = '/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin'
  }
  parameters {
        choice(
            name: 'PLATFORM',
            description: 'For what platform (OS) need to test',
            choices: [
                'centos-6',
                'centos-7',
                'debian-9',
                'debian-10',
                'ubuntu-bionic',
                'ubuntu-xenial',
                'ubuntu-focal',
                'rhel8'
            ]
        )
        choice(
            name: 'REPO',
            description: 'Repo for testing',
            choices: [
                'testing',
                'experimental',
                'release'
            ]
        )
  }
  stages {
    stage('Set build name'){
      steps {
                script {
                    currentBuild.displayName = "${env.BUILD_NUMBER}-${env.PLATFORM}"
                }
            }
        }
    stage ('Prepare') {
      steps {
        checkout scm
        sh '''
            sudo yum install -y gcc python3-pip python3-devel libselinux-python openssl-devel
            sudo mkdir -p /usr/local/lib64/python3.7/site-packages
            sudo rsync -aHv /usr/lib64/python2.7/site-packages/*selinux* /usr/local/lib64/python3.7/site-packages/
            pip3 install --user molecule==2.22 pytest ansible wheel boto boto3 paramiko selinux
        '''
      }
    }
    stage ('Create virtual machines') {
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'MOLECULE_AWS_PRIVATE_KEY', keyFileVariable: 'MOLECULE_AWS_PRIVATE_KEY', passphraseVariable: '', usernameVariable: ''),
        [$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: '4462f2e5-f01c-4e3f-9586-2ffcf5bf366a', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
          sh '''
              cd molecule/pdmysql/pdmysql-ps
              molecule create -s "${PLATFORM}"
          '''
        }
      }
    }
    stage ('Run playbook for test') {
      steps {
        sh '''
            cd molecule/pdmysql/pdmysql-ps
            molecule converge -s "${PLATFORM}"
        '''
      }
    }
    stage ('Start testinfra tests') {
      steps {
        sh '''
            cd molecule/pdmysql/pdmysql-ps
            molecule verify -s "${PLATFORM}"
        '''
        junit "molecule/pdmysql/pdmysql-ps/molecule/${PLATFORM}/report.xml"
      }
    }
    stage ('Start packages deletion') {
      steps {
        sh '''
            cd molecule/pdmysql/pdmysql-ps
            molecule cleanup -s "${PLATFORM}"
        '''
      }
    }
  }
  post {
    always {
      withCredentials([sshUserPrivateKey(credentialsId: 'MOLECULE_AWS_PRIVATE_KEY', keyFileVariable: 'MOLECULE_AWS_PRIVATE_KEY', passphraseVariable: '', usernameVariable: ''),
      [$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: '4462f2e5-f01c-4e3f-9586-2ffcf5bf366a', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
        sh '''
            cd molecule/pdmysql/pdmysql-ps
            molecule destroy -s "${PLATFORM}"
        '''
      }
    }
  }
}
