---
driver:
  name: default
  options:
    managed: true

platforms:
  - name: debian11
    image: ${HOME}/qemu-images/debian-11-genericcloud-amd64.raw
    memory: 2048
    cpus: 2
    disk_size: 20G
    ssh_port: 2230
    ssh_user: debian
    ssh_key: ~/.ssh/id_rsa

provisioner:
  name: ansible
  log: true
  playbooks:
    create: ../shared/create.yml
    prepare: ../shared/prepare.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/converge.yml

verifier:
  name: ansible
