---
# This playbook does following:
#   enables Percona testing repository
#   installs latest version of PS 8.0, PXB 8.0 tarball
#   then runs some tests

- hosts: all
  become: true
  become_method: sudo
  vars:
#    binary_type: "{{ lookup('env', 'binary_type') }}"
    install_repo: "{{ lookup('env', 'install_repo') }}"
    install_mysql_shell: "{{ lookup('env', 'install_mysql_shell', default='') }}"
    gnupg_home: /root/.gnupg
    percona_key1: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    percona_key1_file: "{{ gnupg_home }}/PERCONA-PACKAGING-KEY"
  tasks:
  - name: "[SETUP] Test environment setup"
    include_tasks: ../tasks/test_prep.yml

  - name: "[SETUP] Install libev (Debian)"
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - libev4
    when: ansible_facts['os_family'] == "Debian"

  - name: "[SETUP] Install libev (RedHat)"
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - libev
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[SETUP] Enable main repo"
    include_tasks: ../tasks/enable_main_repo.yml
    when: lookup('env', 'install_repo') == "main"

  - name: "[PS-REPO] Enable PS 8.0 main repo
    include_tasks: ../tasks/enable_ps8_main_repo.yml"
    when: lookup('env', 'install_repo') == "main"

  - name: "[PS-REPO] Enable PS 8.0 testing repo
    include_tasks: ../tasks/enable_ps8_testing_repo.yml"
    when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

  - name: "[PS-REPO] Enable PS 8.0 experimental repo"
    include_tasks: ../tasks/enable_ps8_experimental_repo.yml
    when: lookup('env', 'install_repo') == "experimental"

  - name: "[DEBUG-REPOS] Verify repos after PS repo enable"
    include_tasks: ../tasks/debug_repos.yml

  - name: "[SETUP] Download world database"
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql
  - name: "[PS-INSTALL] Install Percona Server 8.0"
    include_tasks: ../tasks/install_ps80.yml

  - name: "[PXB-TEST] Test PXB 8.0 normal tarball"
    command: /package-testing/test_binary_tarball.sh pxb80 {{ install_repo }} normal

  - name: "[PS-START] Start mysql service (RHEL 6)"
    command: service mysql start
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 6

  - name: "[PS-START] Start mysql service (RHEL 7+)"
    command: systemctl start mysql
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 7

  - name: "[PS-START] Set root password (RedHat)"
    command: /package-testing/setpass_57.sh
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PXB-TEST] Install plugins and import world database"
    command: /package-testing/plugins_test.sh

  - name: "[PXB-TEST] Run backup (RedHat)"
    command: pxb80/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/ --socket=/var/lib/mysql/mysql.sock
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PXB-TEST] Run backup (Debian)"
    command: pxb80/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/
    when: ansible_facts['os_family'] == "Debian"

  - name: "[PXB-TEST] Prepare backup"
    command: pxb80/bin/xtrabackup --prepare --target-dir=/tmp/backups/

  - name: "[PXB-TEST] Run backup with streaming and encryption (RedHat)"
    shell: pxb80/bin/xtrabackup --backup --user=root --target-dir=backups/ --socket=/var/lib/mysql/mysql.sock --encrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly --stream=xbstream --parallel=10 > backup.stream
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PXB-TEST] Run backup with streaming and encryption (Debian)"
    shell: pxb80/bin/xtrabackup --backup --user=root --target-dir=backups/ --encrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly --stream=xbstream --parallel=10 > backup.stream
    when: ansible_facts['os_family'] == "Debian"

  - name: "[PXB-TEST] Extract and decrypt backup"
    shell: pxb80/bin/xbstream --directory=backups/ --extract --decrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly < backup.stream

  - name: "[PXB-TEST] Prepare backup"
    command: pxb80/bin/xtrabackup --prepare --target-dir=backups/

  - name: "[PXB-TEST] Remove backup files"
    command: rm -r pxb80 backups /tmp/backups

  - name: "[PXB-TEST] Test PXB 8.0 minimal tarball"
    command: /package-testing/test_binary_tarball.sh pxb80 {{ install_repo }} minimal

  - name: "[PXB-TEST] Run backup (RedHat)"
    command: pxb80/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/ --socket=/var/lib/mysql/mysql.sock
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PXB-TEST] Run backup (Debian)"
    command: pxb80/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/
    when: ansible_facts['os_family'] == "Debian"

  - name: prepare backup
    command: pxb80/bin/xtrabackup --prepare --target-dir=/tmp/backups/

  - name: "[PXB-TEST] Run backup with streaming and encryption (RedHat)"
    shell: pxb80/bin/xtrabackup --backup --user=root --target-dir=backups/ --socket=/var/lib/mysql/mysql.sock --encrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly --stream=xbstream --parallel=10 > backup.stream
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PXB-TEST] Run backup with streaming and encryption (Debian)"
    shell: pxb80/bin/xtrabackup --backup --user=root --target-dir=backups/ --encrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly --stream=xbstream --parallel=10 > backup.stream
    when: ansible_facts['os_family'] == "Debian"

  - name: extract and decrypt backup
    shell: pxb80/bin/xbstream --directory=backups/ --extract --decrypt=AES256 --encrypt-key=mAU3Xs5sRcSB7zBEJP1BInPP5lgShKly < backup.stream

  - name: prepare backup
    command: pxb80/bin/xtrabackup --prepare --target-dir=backups/
