---
# This playbook does following:
#   sets main Percona repo
#   installs PS 8.0, PT and PXB 8.0
#   changes repo to testing
#   upgrades packages to the new version
#   does some tests
#

# Cosmic is still missing python
# - import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
    install_mysql_shell: "{{ lookup('env', 'install_mysql_shell', default='') }}"
    gnupg_home: /root/.gnupg
    percona_key1: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    percona_key1_file: "{{ gnupg_home }}/PERCONA-PACKAGING-KEY"
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
  tasks:
  - name: "[SETUP] Test environment setup"
    include_tasks: ../tasks/test_prep.yml

# Install from testing repository

#  - name: include tasks for enabling main repo
#    include_tasks: ../tasks/enable_main_repo.yml

  - name: "[PS-REPO] Enable PS 8.0 main repo"
    include_tasks: ../tasks/enable_ps8_main_repo.yml

  - name: "[DEBUG-REPOS] Verify repos after PS main repo enable"
    include_tasks: ../tasks/debug_repos.yml

  - name: "[SETUP] Download world database"
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: "[SETUP] Install libgflags-dev (RHEL9 aarch64)"
    package:
      name: https://dl.fedoraproject.org/pub/epel/9/Everything/aarch64/Packages/g/gflags-2.2.2-9.el9.aarch64.rpm
      state: present
      disable_gpg_check: yes
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] | int >= 9
      - ansible_architecture == "aarch64"

  - name: "[SETUP] Install libgflags-dev (RHEL9 amd64)"
    package:
      name: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/g/gflags-2.2.2-9.el9.x86_64.rpm
      state: present
      disable_gpg_check: yes
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] | int >= 9
      - ansible_architecture != "aarch64"

# Disable Percona Toolkit installation till its supported in OL9 and Jammy
#  - name: install Percona Toolkit new deb packages
#    include_tasks: ../tasks/install_pt.yml

  - name: "[PS-INSTALL] Install Percona Server 8.0"
    include_tasks:
      file: ../tasks/install_ps80.yml
      apply:
        environment:
          PERCONA_TELEMETRY_DISABLE: "1"
    when:
      - lookup('env', 'server_to_test') == "ps-80"

   #### FOR AL2023 ######
  - name: "[PS-REPO] Enable PS 8.0 PRO repo (AL2023)"
    include_tasks: ../tasks/enable_ps80_pro_tools_repo.yml
    when:
      - lookup('env', 'REPO_TYPE') == "PRO"
      - ansible_facts['distribution_major_version'] | int == 2023

  - name: "[PS-INSTALL] Install Percona Server PRO 8.0 (AL2023)"
    include_tasks: ../tasks/install_ps80.yml
    vars:
      pro_suf: "{{ '-pro' if lookup('env', 'REPO_TYPE') == 'PRO' else '' }}"
    when:
      - lookup('env', 'REPO_TYPE') == 'PRO'
      - ansible_facts['distribution_major_version'] | int == 2023
##########

# INSTALL MS 

  - name: "[SETUP] Extract PXB major and minor version"
    shell: cat /package-testing/VERSIONS | grep 'PXB80_VER' | cut -d'=' -f2 | sed 's/"//g'
    register: pxb_version_major_minor_register

  - name: "[SETUP] Extract PXB major version"
    shell: cat /package-testing/VERSIONS | grep PXB80_VER | awk -F'[=".]' '{print $3"."$4}'
    register: pxb_version_major_register

  - name: "[SETUP] Extract numeric major release version"
    shell: cat /package-testing/VERSIONS | grep -oP 'PXB80_VER="\K(\d+)\.(\d+)' | tr -d '.'
    register: major_release_version_register

  - name: "[SETUP] Set major_release_version fact"
    set_fact:
      major_release_version_reg: "{{ major_release_version_register.stdout }}"

  - name: "[SETUP] Set pxb_version_major fact"
    set_fact:
      pxb_version_major_reg: "{{ pxb_version_major_register.stdout }}"

  - name: "[SETUP] Set pxb_version_major_minor fact"
    set_fact:
      pxb_version_major_minor_reg: "{{ pxb_version_major_minor_register.stdout }}"

  - name: "[SETUP] Debug PXB version number"
    debug:
      msg: "PXB version number is {{ pxb_version_major_reg }} {{ pxb_version_major_minor_reg }}"

  - name: "[MS-INSTALL] Install MySQL MS Server"
    include_tasks: ../tasks/install_ms_innovation.yml
    vars:
      pxb_version_major: "{{ pxb_version_major_reg }}"
      pxb_version_major_minor: "{{ pxb_version_major_minor_reg }}"
    when:
      - lookup('env', 'server_to_test') == "ms-80"
##

  - name: "[PXB-REPO] Enable PXB 8.0 main repo"
    include_tasks: ../tasks/enable_pxb_80_main_repo.yml
    when:
      - lookup('env', 'REPO_TYPE') !="PRO"

  - name: "[DEBUG-REPOS] Verify repos after PXB main repo enable"
    include_tasks: ../tasks/debug_repos.yml

  - name: "[PXB-INSTALL] Install PXB 8.0 (main repo)"
    include_tasks:
      file: ../tasks/install_pxb80.yml
      apply:
        environment:
          PERCONA_TELEMETRY_DISABLE: "1"
    when:
      - lookup('env', 'REPO_TYPE') !="PRO"

#####Enable and install PXB 80 PRO ###########
  - name: "[PXB-REPO] Enable PXB 8.0 PRO repo (release, RedHat)"
    include_tasks: ../tasks/enable_pxb80_pro_repo.yml
    vars:
      repo: "release"
    when:
      - lookup('env', 'REPO_TYPE') == "PRO"
      - lookup('env', 'server_to_test') == "ps-80"
      - ansible_facts['os_family'] == "RedHat"

  - name: "[PXB-REPO] Enable PXB 8.0 PRO repo (main, Debian)"
    include_tasks: ../tasks/enable_pxb80_pro_repo.yml
    vars:
      repo: "main"
    when:
      - lookup('env', 'REPO_TYPE') == "PRO"
      - lookup('env', 'server_to_test') == "ps-80"
      - ansible_facts['os_family'] == "Debian"

  - name: "[PXB-INSTALL] Install PXB 8.0 PRO (main repo)"
    include_tasks: ../tasks/install_pxb80_pro.yml
    when:
      - lookup('env', 'REPO_TYPE') == "PRO"
      - lookup('env', 'server_to_test') == "ps-80"
##############################################


  - name: "[PXB-UPGRADE] Print PXB version before upgrade"
    shell: |
      {
        echo "XTRABACKUP VERSION is ";
        xtrabackup --version || echo "FAILED: xtrabackup --version";
        echo "xbstream VERSION is ";
        xbstream --version || echo "FAILED: xbstream --version";
        echo "xbcloud VERSION is ";
        xbcloud --version || echo "FAILED: xbcloud --version";
        echo "xbcrypt VERSION is ";
        xbcrypt --version || echo "FAILED: xbcrypt --version";
        echo "list rpm packages ";
        rpm -qa | grep "percona" || echo "FAILED: rpm -qa | grep percona";
        echo "list deb packages";
        dpkg -l | grep "percona" || echo "FAILED: dpkg -l | grep percona";
      }
    register: version_output_pre_upgrade
    ignore_errors: yes

  - name: "[PXB-UPGRADE] Display PXB version before upgrade"
    debug:
      var: version_output_pre_upgrade.stdout_lines

  - name: "[PS-START] Start mysql service (RHEL, main repo)"
    command: systemctl start mysqld
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PS-START] Set root password (RedHat, main repo)"
    command: /package-testing/setpass_57.sh
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PS-START] Copy .my.cnf (RedHat, main repo)"
    template: src=../templates/my_57.j2
              dest=/root/.my.cnf
              mode=0640 owner=root group=root
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PS-START] Restart mysqld service (RedHat, main repo)"
    service: name=mysqld state=restarted
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PS-START] Restart mysql service (Debian)"
    service: name=mysql state=restarted
    when: ansible_facts['os_family'] == "Debian"

  - name: "[PXB-TEST] Install plugins and import world database"
    command: /package-testing/plugins_test.sh

  - name: "[SETUP] Install 3rd party packages (Debian)"
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - rsyslog-mysql
    when: ansible_facts['os_family'] == "Debian"

  - name: "[PS-REPO] Enable PS 8.0 testing repo (upgrade)"
    include_tasks: ../tasks/enable_ps8_testing_repo.yml
    when:
      - lookup('env', 'REPO_TYPE') !="PRO"

  - name: "[PXB-REPO] Enable PXB 8.0 testing repo (upgrade)"
    include_tasks: ../tasks/enable_pxb_80_testing_repo.yml
    when:
      - lookup('env', 'REPO_TYPE') !="PRO"

# Upgrade packages
#

#####Enable and install PXB 80 PRO Testing ###########
  - name: "[PXB-REPO] Enable PXB 8.0 PRO testing repo"
    include_tasks: ../tasks/enable_pxb80_pro_repo.yml
    vars:
      repo: "testing"
    when:
      - lookup('env', 'REPO_TYPE') == "PRO"
      - lookup('env', 'server_to_test') == "ps-80"

  - name: "[PXB-INSTALL] Install PXB 8.0 PRO (testing)"
    include_tasks: ../tasks/install_pxb80_pro.yml
    when:
      - lookup('env', 'REPO_TYPE') == "PRO"
      - lookup('env', 'server_to_test') == "ps-80"
##############################################



  - name: "[PXB-INSTALL] Install PXB 8.0 (testing, upgrade)"
    include_tasks:
      file: ../tasks/install_pxb80.yml
      apply:
        environment:
          PERCONA_TELEMETRY_DISABLE: "1"
    when:
      - lookup('env', 'REPO_TYPE') !="PRO"

  - name: "[PXB-UPGRADE] Print PXB version after upgrade"
    shell: |
      {
        echo "XTRABACKUP VERSION is ";
        xtrabackup --version || echo "FAILED: xtrabackup --version";
        echo "xbstream VERSION is ";
        xbstream --version || echo "FAILED: xbstream --version";
        echo "xbcloud VERSION is ";
        xbcloud --version || echo "FAILED: xbcloud --version";
        echo "xbcrypt VERSION is ";
        xbcrypt --version || echo "FAILED: xbcrypt --version";
        echo "list rpm packages ";
        rpm -qa | grep "percona" || echo "FAILED: rpm -qa | grep percona";
        echo "list deb packages";
        dpkg -l | grep "percona" || echo "FAILED: dpkg -l | grep percona";
      }
    register: version_output_post_upgrade
    ignore_errors: yes


  - name: "[PXB-UPGRADE] Display PXB version after upgrade"
    debug:
      var: version_output_post_upgrade.stdout_lines

  - name: "[PXB-TEST] Check telemetry (disabled)"
    command: /package-testing/check_telemetry.sh pxb -d
    when:
      - lookup('env', 'REPO_TYPE') !="PRO"

  - name: "[PXB-TEST] Check PXB version after upgrade"
    command: /package-testing/version_check.sh pxb80

  - name: "[PXB-TEST] Check PXB package versions are correct"
    command: /package-testing/package_check.sh pxb80
    when:
      - lookup('env', 'REPO_TYPE') !="PRO"

#  - name: check that Percona XtraBackup package versions are correct
#    command: /package-testing/package_check.sh pxb80 pro
#    when:
#      - lookup('env', 'REPO_TYPE') == "PRO"

  - name: "[PXB-TEST] Run backup"
    command: /usr/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/

  - name: "[PXB-TEST] Prepare backup"
    command: /usr/bin/xtrabackup --prepare --user=root --target-dir=/tmp/backups/

  - name: "[PS-CLEANUP] Remove Percona Server deb packages"
    apt:
      name: "{{ packages }}"
      update_cache: no
      state: absent
    vars:
      packages:
      - percona-server-server
      - percona-xtrabackup-80
    when:
      - ansible_facts['os_family'] == "Debian"
      - lookup('env', 'server_to_test') == "ps-80"
      - lookup('env', 'REPO_TYPE') !="PRO"

  - name: "[PS-CLEANUP] Remove Percona Server rpm packages"
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - percona-server-server
      - percona-xtrabackup-80
    when:
      - ansible_facts['distribution'] in ["RedHat", "CentOS", "OracleLinux", "Amazon", "Rocky"]
      - lookup('env', 'server_to_test') == "ps-80"
      - lookup('env', 'REPO_TYPE') !="PRO"

## Changes done for telemetry: add iptables rule for Telemetry Server - install only pxb package.
## Expected resuld - telemetry_uuid file has only instanceID

  - name: "[SETUP] Install iptables (RHEL)"
    dnf:
      name:
        - iptables
        - iptables-services
      state: present
    when:
      - ansible_facts['distribution'] in ["RedHat", "CentOS", "OracleLinux", "Amazon", "Rocky"]

  - name: "[SETUP] Enable and start iptables"
    systemd:
      name: iptables
      state: started
      enabled: true
    when: ansible_facts['distribution'] == "RedHat"

  - name: "[SETUP] Block telemetry IP"
    iptables:
      chain: OUTPUT
      destination: check-dev.percona.com
      jump: DROP
    when:
      - lookup('env', 'upgrade_repo') == ""

  - name: "[PXB-INSTALL] Install PXB for telemetry"
    include_tasks: ../tasks/install_pxb80.yml
    when:
       - lookup('env', 'REPO_TYPE') !="PRO"

  - name: "[PXB-TEST] Check telemetry (uuid)"
    command: /package-testing/check_telemetry.sh pxb -u
    when:
      - lookup('env', 'server_to_test') != "ms-80"
      - lookup('env', 'REPO_TYPE') !="PRO"

  - name: "[PS-CLEANUP] Remove PXB packages for telemetry"
    include_tasks: ../tasks/remove_pxb80.yml
