---
# This playbook sets up the percona repo

# - import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
    gnupg_home: /root/.gnupg
    percona_key1: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    percona_key1_file: "{{ gnupg_home }}/PERCONA-PACKAGING-KEY"
  tasks:
  - name: "[SETUP] Test environment setup"
    include_tasks: ../tasks/test_prep.yml

  - name: "[MS-UPSTREAM] Install MySQL apt repository"
    apt:
      deb: https://repo.mysql.com/mysql-apt-config_0.8.32-1_all.deb
    when: ansible_facts['os_family'] == "Debian"

  - name: "[MS-UPSTREAM] Install MySQL RHEL 7 yum repository"
    yum: name=https://repo.mysql.com/mysql84-community-release-el7.rpm state=present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 7

  - name: "[MS-UPSTREAM] Import MySQL GPG key"
    rpm_key:
      state: present
      key: http://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8

  - name: "[MS-UPSTREAM] Install MySQL RHEL 8 yum repository"
    yum: name=https://repo.mysql.com/mysql84-community-release-el8.rpm state=present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 8

  - name: "[MS-UPSTREAM] Install MySQL RHEL 9 yum repository"
    yum: name=https://repo.mysql.com/mysql84-community-release-el9-1.noarch.rpm state=present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 9

  - name: "[SETUP] Enable EPEL 7 repo"
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 7

  - name: "[SETUP] Enable EPEL 8 repo"
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm state=present
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 8

  - name: "[SETUP] Download world database"
    command: "{{ item }}"
    with_items:
    - wget --no-check-certificate -P /package-testing https://raw.githubusercontent.com/Percona-QA/percona-qa/master/sample_db/world.sql

  - name: "[MS-UPSTREAM] Disable mysql module (RHEL 8)"
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 8

  - name: "[SETUP] Install base deb packages"
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - vim
      - pv
      - unzip
    when: ansible_facts['os_family'] == "Debian"

  - name: "[MS-UPSTREAM] Install MySQL Community (Debian)"
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - mysql-community-server
    when: ansible_facts['os_family'] == "Debian"

  - name: "[MS-UPSTREAM] Install MySQL Community (RHEL 7)"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - libselinux-python
      - pv
      - unzip
      - mysql-community-server
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int <= 7

  - name: "[MS-UPSTREAM] Install MySQL Community (RHEL 8+)"
    package:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python3-libselinux
      - mysql-community-server
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int >= 8

  - name: "[PS-START] Start mysql service (Debian)
    service: name=mysql state=started"
    when: ansible_facts['os_family'] == "Debian"

  - name: "[PS-START] Start mysqld service (RHEL)
    service: name=mysqld state=started"
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[PS-START] Set root password (RedHat)"
    command: /package-testing/setpass_57.sh
    when: ansible_facts['os_family'] == "RedHat"

  - name: "[SETUP] Enable tools testing repo"
    include_tasks: ../tasks/enable_tools_testing_repo.yml

  - name: "[PXB-REPO] Enable PXB 8.4 repo"
    command: percona-release enable-only pxb-84-lts testing

  - name: "[DEBUG-REPOS] Verify repos before PXB install"
    include_tasks: ../tasks/debug_repos.yml

  - name: "[PXB-INSTALL] Install PXB 8.4"
    include_tasks: ../tasks/install_pxb84.yml

  - name: "[PXB-TEST] Install plugins and import world database"
    command: /package-testing/plugins_test.sh

  - name: "[PXB-TEST] Check PXB version is correct"
    command: /package-testing/version_check.sh pxb84

  - name: "[PXB-TEST] Check PXB package versions are correct"
    command: /package-testing/package_check.sh pxb84

  - name: "[PXB-TEST] Run backup"
    command: /usr/bin/xtrabackup --backup --user=root --target-dir=/tmp/backups/

  - name: "[PXB-TEST] Prepare backup"
    command: /usr/bin/xtrabackup --prepare --user=root --target-dir=/tmp/backups/
